project:
  type: book

book:
  title: "Iqtisodchi va boshqalar uchun yon daftar"
  author: "Nozimjon Ortiqov"
  date: "23.11.2023"
  chapters:
    - index.qmd
    - intro.qmd
    - importisnotsobad.qmd
    - accounting_identities.qmd
    - inflyatsiya.qmd
    - realvsnominal.qmd
    - percentage_change.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

