project:
  type: book
  output-dir: docs

book:
  title: "Iqtisodchi va boshqalar uchun yon daftar"
  search: true
  repo-url: https://github.com/nozimmjon/econ_001
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  author: "Nozimjon Ortiqov"
  date: "23/11/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - importisnotsobad.qmd
    - accounting_identities.qmd
    - inflyatsiya.qmd
    - realvsnominal.qmd
    - percentage_change.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [pulse, style.scss]
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual
comments:
  hypothesis: true
