# Import vs Yalpi ichki mahsulot (YaIM)

**Yalpi ichki mahsulot (YaIM)** - **mamlakat hududida** ma'lum davr (yil yoki chorak) mobaynida yaratilgan tovar va xizmatlar umumiy qiymatidir.

Ushbu ta'rifni bir muhim jihati bor:

| **Mamlakat tashqarisida yaratilgan mahsulotlar (import) YaIM tarkibiga kirmaydi**.

Ammo, juda ko'pchilik *import YaIMni kamaytiradi deb o'ylaydi*, hattoki professional iqtisodchi va nufuzli jurnallar ham.

Ushbu xatolik milliy hisoblar tizimidagi ayniyatdan kelib chiqadi. Unga ko'ra, YaIM xarajatlar usulida quyidagicha hisoblanadi:

$Y = C + I + G+(X-M)$ .

::: aside
*Bu yerda, Y - yalpi ichki mahsulot, C - iste'mol, I-investitsiya, G-davlat xarajatlari, X-eksport, M - import.*
:::

Ushbu ayniyatda M-import chegirib tashlanishi xato xulosaga olib keladi. Qolgan elementlar qo'shilyapti, import ayrilyapti. Shundan kelib chiqib, ko'pchilik "*importni kamaytirsak, YaIM ko'payadi*", yoki "*import ko'paygani hisobiga YaIM o'sishi sekinlashdi*" deb xulosa qiladi.

Unda nega tepada import chegirilmoqda?

Sababi juda oddiy, [**import YaIM tarkibida o'tirmaydi**]{.underline}.

Iste'mol (investitsiya, davlat) xarajatlari tarkibida mamlakatda ishlab chiqarilgan mahsulotlar bilan birga import ham o'tiradi.

Misol uchun, yangi Iphone telefon sotib oldingiz, bu iste'molingizni bir qismi. Ammo, ichki, mahalliy (domestic) mahsulot emas - O'zbekistonda ishlab chiqarilmagan. Shuning uchun, ushbu xarajatni YaIMni hisoblashda chegirib tashlash kerak.

Savol tug'ilishi mumkin, nima uchun birdaniga iste'mol, investitsiya yoki davlat xarajatlaridan importni chegirib, yuqoridagi tenglamadan import komponenti olib tashlanmaydi va quyidagicha ifoda qilinmaydi?

$Y = C + I + G+X$

Sababi, iste'mol, investitsiya va davlat xarajatlari umumiy (aggregated) ko'rsatkich va ushbu xarajatlar kelib chiqish manbasi bo'yicha alohida statistika yuritilmaydi. Sizdan yil davomidagi iste'molingizning qanchasi import mahsulotlar deb so'rashsa, aniq ayta olmaysiz yoki buning hisobini yuritmaysiz.

Shuning uchun, statistikasi yuritiladigan umumiy iste'mol (investitsiya)dan statistikasi bor bo'lgan umumiy import komponenti olib tashlanadi.

Yuqoridagi YaIM formulasini quyidagicha ifoda qilish orqali yana ham aniqroq tushunish mumkin:

$Y = (C~d~ + C~f~ ) + (I~d~ + I~f~) + (G~d~ + G~f~) +(X- [C~f~ +I~f~ + G~f~])$

Bunda Iste'mol (Investitsiya, Davlat) xarajatlari ichki va tashqi komponentlarga ajratilgan.

Mazkur formula yordamida bir misol ko'raylik.

Tasavvur qilaylik, davlatda Iste'mol 100ga, Investitsiya, Davlat xarajatlari, Eksport va Import esa nol bo'lsin. Shunda, YaIM 100 ga teng bo'ladi:

$Y = (100+0) + 0 + 0 + (0-0)$

Endi, ushbu gipotetik davlat tashqi bozorga ochilib, 100 birlik import qilsin va uni iste'mol qilsin. U holda tenglikni quyidagicha yozish mumkin:

$Y = (100+100) + 0 + 0 + (0-100)$

Ushbu misolni soddalashtirsak, YaIM 100 ga teng bo'ladi. Bunda iste'mol 200, ammo YaIM hajmi o'zgarmasdan qoladi.

Mazkur misoldan ko'rish mumkinki, **import YaIM hajmiga ta'sir ko'rsatmaydi** va faqat bir xarajatni ikki marta hisobga olmaslik uchun korrektirovka qilinyapti.

Demak,

1.  YaIM mamlakat hududida yaratilgan tovar va xizmatlarni o'z ichiga oladi.
2.  Import uchun sarflangan xarajatlarni YaIMni hisoblashda chegirib tashlash kerak.
3.  Import to'g'ridan-to'g'ri YaIMni kamaytirmaydi.

Endi, kimdir aytishi mumkin, import ko'paysa milliy mahsulotlarni sotib olish kamayadi va bu YaIMni kamaytiradi deb.

**Bu bizni yana bir xatoga yetaklaydi - ayniyatdan (formula) sabab-oqibatni keltirib chiqarish**. Bu haqida keyingi qismda to'xtalamiz.
